name: Python Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome (latest stable)
        uses: browser-actions/setup-chrome@v1

      - name: Run tests
        run: |
          pytest --headless --browser=chrome --alluredir=allure-results
